### ISSUE TITLE
Black Frames

### ISSUE THREAD

**Issue by Haeri** [kode80/UnityTools#1]
Issue description: All captured frames are just black.

This issue is certainly not directly caused by your script, but has something to do with the behavior of Application.CaptureScreenshot(). I have experimented and changed around some settings, but still couldn't find the exact cause for this problem. What I suspect is that it has something to do with high performance load not allowing the screen-capture to work properly. For example setting everything to low quality, removing all post-effects and having "Maximize on Play" disabled, seems to work.

Would be great if you could help me out on this one. I really like this script :)

My specs:
Windows Home 10 64-bit
Unity 5.3.1p2
NVIIDIA GeForce GTX 550 Ti
Intel-Core i7-2600
8Gig RAM

**Comment by kode80** [comment]
The one thing that keeps coming up when I read about this issue is antialiasing. Could you try leaving all your quality settings on high but disable AA and see if that has any effect?

I'm running on a MBP which is slightly lower specs than your machine and even when putting every image effect imaginable on the camera, with a highly detailed scene + setting super size to 4x, I can't reproduce the black frame issue. The capture takes a very long time (as expected) but I always get correctly rendered frames.

If disabling AA still doesn't fix it, could you post a little more about your scene? Deferred/forward, list specific image effects you're using etc.

**Comment by Haeri** [comment]
Ok yes I can confirm it's the Anti Aliasing that is causing the issue. I was just checking the wrong AA. It is NOT the post-processing AA but the AA inside the quality settings that needs to be disabled. I assume this is a Unity bug?

**Comment by kode80** [comment]
Cool, glad we got to the bottom of it. Yeah it's a Unity bug, I've found forum posts stretching back 5 years ago that mention it, supposedly it was fixed - but evidently not in all cases. HW antialiasing doesn't seem to cause this issue for me (under both OSX + Win) so my guess is it's a specific card/driver issue.

I'll update the readme to mention this issue + workaround.
